// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxSDKqsiNECeY_QeSYX33-Zl_IL82E92k',
    appId: '1:845349522585:android:f7ebcaa64fc28b8dce7c08',
    messagingSenderId: '845349522585',
    projectId: 'salon-management-21945',
    authDomain: 'salon-management-21945.firebaseapp.com',
    storageBucket: 'salon-management-21945.appspot.com',
    measurementId: 'G-MEASUREMENT_ID', // Replace with actual measurement ID
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxSDKqsiNECeY_QeSYX33-Zl_IL82E92k',
    appId: '1:845349522585:android:f7ebcaa64fc28b8dce7c08',
    messagingSenderId: '845349522585',
    projectId: 'salon-management-21945',
    storageBucket: 'salon-management-21945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_lBXfkDmgf0neQrxOKPc2HRhD7GdILjk',
    appId: '1:845349522585:ios:6687ac6411be23cdce7c08',
    messagingSenderId: '845349522585',
    projectId: 'salon-management-21945',
    storageBucket: 'salon-management-21945.appspot.com',
    iosClientId: '845349522585-87qd4t521u29t4obqerpqtd2uolfa2qq.apps.googleusercontent.com',
    iosBundleId: 'salon-management-21945',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_lBXfkDmgf0neQrxOKPc2HRhD7GdILjk',
    appId: '1:845349522585:ios:6687ac6411be23cdce7c08',
    messagingSenderId: '845349522585',
    projectId: 'salon-management-21945',
    storageBucket: 'salon-management-21945.appspot.com',
    iosClientId: '845349522585-87qd4t521u29t4obqerpqtd2uolfa2qq.apps.googleusercontent.com',
    iosBundleId: 'salon-management-21945',
  );
}
